### ISSUE TITLE
Hello, on functional phones, events can't be used (up and down, and enter keys can't be used). Also, please ask (l10.js) what is the role of this JavaScript file, thank you.

### ISSUE THREAD

**Issue by dixiaoping** [robnyman/Firefox-OS-Boilerplate-App#68]

**Comment by Mte90** [comment]
Hi, this project is abandoned also because Firefox OS is not developed anymore and during this month also the FXOS marketplace will be closed.

**Comment by Ryuno-Ki** [comment]
@robnyman Maybe you should archive this repo …

**Comment by robnyman** [comment]
Hi,

Yeah, I thought about it but since Firefox OS still exists in some places, I was thinking it might be useful there. Also, I think there's a certain novelty/nostalgic value of keeping this here. :-) And hoping that people who look at it and try to implement things really only do it in a Firefox OS context.
